#!/bin/sh

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )

export SPREAD_CORE_ARCH=i386
export SPREAD_CORE_CHANNEL=stable
cd target && ../bin/spread -v linode:
