#!/bin/sh

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
git clone https://github.com/snapcore/snapd target

export SPREAD_REMOTE_STORE=staging

cd target || exit
../bin/spread -v linode:ubuntu-14.04-64 linode:ubuntu-16.04-64 linode:ubuntu-16.04-32 linode:ubuntu-core-16-64 linode:debian-unstable-64

