#!/bin/sh
set -e

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
git clone https://github.com/snapcore/snapd target

cd target || exit 1

# TODO: Remove when conjureup snapd is propoted to stable
sed 's/SNAP\/conjureup/#SNAP\/conjureup/g -i tests/main/install-snaps/task.yaml'
# TODO: Remove when is fixed the issue raised on https://forum.snapcraft.io/t/error-installing-the-docker-snap-in-fedora-and-opensuse/1655
sed 's/SNAP\/docker/#SNAP\/docker/g -i tests/main/install-snaps/task.yaml'
../bin/spread -v linode:tests/main/install-snaps
